### ISSUE TITLE
Can't toggle developer mode with tray icon disabled

### ISSUE THREAD

**Issue by ppvg** [KELiON/cerebro#113]
With "show in menu bar" disabled, toggling developer mode throws an uncaught exception:

```
TypeError: Cannot read property 'setContextMenu' of null
    at AppTray.setIsDev (/app/main/createWindow/AppTray.js:32:5)
    at EventEmitter._electron.ipcMain.on (/app/main.development.js:77:10)
```

**Comment by KELiON** [comment]
@ppvg yep, easy to reproduce, going to fix it
