### ISSUE TITLE
App search is not working [Lubuntu 16.04]

### ISSUE THREAD

**Issue by vadimstrukov** [KELiON/cerebro#128]
Just installed latest version through AppImage, but cerebro is not searching my applications
![image](https://cloud.githubusercontent.com/assets/8940128/23183460/cbec9894-f884-11e6-8f36-5393edddd24e.png)

**Comment by kion** [comment]
Same on Ubuntu 16.10. Installed Cerebro via deb.

**Comment by rafa-acioly** [comment]
same on ubuntu 16.10. Installed Cerebro via `.AppImage`

**Comment by elmerehbi** [comment]
I am running it on Ubuntu Gnome 16.04 (running using `npm run package`; didn't figure out how to install) and things are working including app search.

**Comment by KELiON** [comment]
Can you please do the following: 

1) Open settings
2) Turn on developer mode, show icon in tray
3) From tray icon choose development -> DevTools (background)
4) From tray icon choose development -> reload
5) And after that send me output of `console` tab of devtools?

/cc @vadimstrukov @kion @rafa-acioly

**Comment by vadimstrukov** [comment]
![image](https://cloud.githubusercontent.com/assets/8940128/23257151/42488eb6-f9cb-11e6-9e49-1656dcb8779c.png)
Interesting.. After i deleted .desktop entry of Fallout2 with bad encoding, everything seems to be working fine and without any errors in console.
![image](https://cloud.githubusercontent.com/assets/8940128/23257296/e44d460c-f9cb-11e6-9bfa-e79b48a1f852.png)

**Comment by kion** [comment]
Confirmed. I had same exact issue caused by .desktop file name encoding. Removing .desktop file fixed the issue for me, but, obviously, it's just a workaround and issue needs a fix.

**Comment by KELiON** [comment]
@vadimstrukov @kion can you paste the real name of broken file (with correct encoding)?

**Comment by markmandel** [comment]
Similar situation, slightly different reason - permissions issue:
```
Uncaught (in promise) Error: EACCES: permission denied, open '/usr/share/applications/jetbrains-idea.desktop'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at parseDesktopFile (file:///opt/Cerebro/resources/app.asar/dist/background.bundle.js:14415:33)
```

Thinking this sort of thing should be caught, logged to console, and then the application should just be ignored, so as to not break anything else?

**Comment by vadimstrukov** [comment]
@KELiON 
.desktop entry has russian word, but with bad wine encoding
