### ISSUE TITLE
Cant install on Antegeros\Arch

### ISSUE THREAD

**Issue by mquiles** [KELiON/cerebro#226]
Just tried installing this and keep getting this error message.

Rebuilding native production dependencies for linux:x64
Error: spawn npm ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at spawn (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder-util/src/util.ts:97:3)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/yarn.ts:118:11
From previous event:
    at rebuild (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/yarn.js:87:22)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/yarn.ts:16:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at installOrRebuild (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/yarn.js:33:21)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/packager.ts:305:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/packager.js:403:11)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/packager.ts:168:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/packager.js:299:11)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/packager.ts:143:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/packager.js:251:11)
    at /tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/src/builder.ts:214:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/builder.js:63:21)
    at Object.<anonymous> (/tmp/yaourt-tmp-mike/aur-cerebro/src/cerebro-0.2.7/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build cerebro.
==> Restart building cerebro ? [y/N]
==> --------------------------------
==>

**Comment by maximbaz** [comment]
Hey @mquiles, please try again, should be fixed now. Even though we use `yarn`, apparently we still require `npm` to build the binaries.

**Comment by prcastro** [comment]
Now it installs here, seems to be fixed

**Comment by mquiles** [comment]
Works great now,  thanks for the quick response.
