### ISSUE TITLE
Cannot find module '../dialog'

### ISSUE THREAD

**Issue by Bartinger** [KELiON/cerebro#324]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Cerebro.app version**: 0.2.8

## Issue
When launching Cerebro I'm getting the following error message in the terminal:

```
/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:0

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Cerebro/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/opt/Cerebro/resources/electron.asar/browser/api/exports/electron.js:37:14)
    at process.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)

```
I tried the AppImage as well as the .deb file.

Thanks

**Comment by KELiON** [comment]
@Bartinger how did you install the app? Did you download it from site?

**Comment by Bartinger** [comment]
@KELiON thanks for the quick response.

I downloaded the AppImage via the Website and the .deb file via the Github releases page. I launched the AppImage with a simple double click and installed the .deb file with gdebi

**Comment by KELiON** [comment]
@Bartinger And after you see this message – does application start? Or it is failed to start?

**Comment by Bartinger** [comment]
@KELiON After killing the program and restarting it the error disappeared.

To answer your question though, I started the app via the terminal and it didn't start (exited with above error). I noticed that an old process was still running (maybe the AppImage?), after killing that Cerebro started working.
