### ISSUE TITLE
Hoe to properly use settings when creating a plugin

### ISSUE THREAD

**Issue by brpaz** [KELiON/cerebro#385]
- [x ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 18.2
- **Cerebro.app version**: 0.3
- **Relevant information from devtools**  NA

## Issue

Hello. I am trying to create a plugin, that will make a call to an external API. That API requires an access token to be set, in order to make requests.
My question is, what is the best way to store that access token? The settings API seems the right way but I cant get  it working.

I have added the following to my plugin configuration:

```
module.exports = {
  fn: plugin,
  name: 'bit.ly URL shortener',
  keyword: 'bitly',
  icon,
  settings: {
    accessToken: {
      type: 'string',
      description: 'bit.ly access token',
    },
  }
};
```

But in the plugin code, `scope.settings`, is always undefined. Also, where the user will be able to configure the plugin with the required settings? In the plugin section? Couldn't find any example of it.

Thank you for your help.

**Comment by KELiON** [comment]
Hey, @brpaz! 
Everything is correct: settings is a good place to store the token and yes, user can set settings in plugins → your plugin name. You can check an example in [translate plugin](https://github.com/KELiON/cerebro-yandex-translate/blob/master/src/index.js). 

There is a problem in latest release of Cerebro, where you can't see plugin that is under development in plugins list. For development of your plugin you would need to check out master branch of Cerebro, where this issue is fixed and run it locally. After that you can type `plugins` and see your plugin on top of results, in `development` section. There you can edit your settings: 

![screen shot 2017-08-17 at 14 56 31](https://user-images.githubusercontent.com/594298/29413318-47f89b4c-835c-11e7-85ef-628a9529a2a1.png)

But it is needed only for development. After publishing your plugin it could be found it list and settings could be edited in latested Cerebro.

Let me know if I can help with something else!

**Comment by brpaz** [comment]
Thanks for your help. Yes, I understood later that my issue was related to the settings not appear for my locally developed plugin.

I will try later with master branch, but for now I pushed my plugin to npm and installed it normally. but I got a problem when open the "settings" menu:

Here is the log:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'accessToken' in undefined
    at t.e (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:274873)
    at Array.map (native)
    at t.e (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:275165)
    at f._renderValidatedComponentWithoutOwnerOrContext (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:617990)
    at f._renderValidatedComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:618217)
    at f.performInitialMount (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:611887)
    at f.mountComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:610381)
    at Object.mountComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:40201)
    at Object.updateChildren (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:604540)
    at le._reconcilerUpdateChildren (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:654518)
```

The same happens in the translate plugin. I cant open the settings and a similar error appear on the console:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'defaultLanguage' in undefined
    at t.e (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:274873)
    at Array.map (native)
    at t.e (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:275165)
    at f._renderValidatedComponentWithoutOwnerOrContext (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:617990)
    at f._renderValidatedComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:618217)
    at f.performInitialMount (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:611887)
    at f.mountComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:610381)
    at Object.mountComponent (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:40201)
    at Object.updateChildren (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:604540)
    at le._reconcilerUpdateChildren (file:///opt/Cerebro/resources/app.asar/dist/main.bundle.js:1:654518)
```

I am missing something?

**Comment by KELiON** [comment]
Yep, I see. Sorry, I gave you wrong information that it works in current release – it doesn't. I'll do a release with fix today, because it is important. But you still can open settings in cerebro master branch

**Comment by brpaz** [comment]
Ok. thank you. I will try with the master branch for now.
