### ISSUE TITLE
could not find machine-id file

### ISSUE THREAD

**Issue by julianorafael** [KELiON/cerebro#41]
Just installed cerebro on Arch Linux and this happened:
```
cat: /var/lib/dbus/machine-id: No such file or directory
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Command failed: cat /var/lib/dbus/machine-id
cat: /var/lib/dbus/machine-id: No such file or directory

    at checkExecSyncError (child_process.js:495:13)
    at execSync (child_process.js:535:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:685:22)
    at c (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:309:7107)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:283:100)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:159:20)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
    at Object.<anonymous> (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:52:22)
    at __webpack_require__ (/tmp/.mount_wzwsP7/usr/bin/resources/app.asar/main.js:21:30)
```

I solved it by creating a sym link to the file that actually was located at `/etc/machine-id` instead of `/var/lib/dbus/machine-id`

**Comment by KELiON** [comment]
@julianorafael I've created an issue in [machine-id](https://github.com/davidwood/machine-id/issues/1) package repository, but in case if this repo is not supported I'll fix it in cerebro only

**Comment by davidwood** [comment]
The `machine-id` project is not the correct project. Per the [dependency in package.json](https://github.com/KELiON/cerebro/blob/master/package.json#L199), the project being used is [node-machine-id](https://github.com/automation-stack/node-machine-id).

**Comment by KELiON** [comment]
@davidwood ouch, sorry, too much similar npm packages
