### ISSUE TITLE
Javascript error when launching Cerebro in Ubuntu 17.10.1 (gnome)

### ISSUE THREAD

**Issue by prakashait09** [KELiON/cerebro#446]
![screenshot from 2018-01-29 22-10-56](https://user-images.githubusercontent.com/24225487/35522229-c47e4f60-0541-11e8-9dcc-4e07db0e5d6d.png)

- [x ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.10.1 (gnome environment)
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: No Info

## Issue
I installed Cerebro using .deb package in Ubuntu 17.10.1. My OS is up to date and Cerebro is latest.
After installing, Hitting Ctrl + Space was doing nothing. So I just launched the Cerebro app manually and what I am getting is below error with a rectangular box (Cerebero screen)
I am using gnome environment with few extensions and wine.

Let me know if you need any other info.

<hr/>

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/opt/Cerebro/resources/app.asar/main.js:251:15)
    at module.exports.exports.default (/opt/Cerebro/resources/app.asar/main.js:915:30)
    at App.module.exports._electron.app.on (/opt/Cerebro/resources/app.asar/main.js:653:43)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

_On clicking OK, another popup comes_

Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at EventEmitter.module.exports._electron.ipcMain.on (/opt/Cerebro/resources/app.asar/main.js:687:47)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/api/web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

**Comment by browniebroke** [comment]
Looks like it's a duplicate of #434.

**Comment by prakashait09** [comment]
you are correct @browniebroke
