### ISSUE TITLE
Exception Object has been destroyed

### ISSUE THREAD

**Issue by benone** [KELiON/cerebro#46]
```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at exports.default.appWindow (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow/toggleWindow.js:6:17)
    at Function.toggleMainWindow (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow.js:34:34)
```

**Comment by KELiON** [comment]
@benone do you have any steps to reproduce it?

**Comment by vandamm** [comment]
@KELiON it's easy:

1. Invoke Cerebro window
2. Press Cmd+W (I'm on Mac)
3. Invoke Cerebro window again

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at exports.default.appWindow (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow/toggleWindow.js:6:17)
    at click (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow/AppTray.js:41:22)
    at MenuItem.click (/Applications/Cerebro.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Cerebro.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15
```

Still happens on 0.2.6

**Comment by KELiON** [comment]
@vandamm thanks! Going to fix it in next release

**Comment by KELiON** [comment]
@AlexAlabyev can you please answer my previous question? I'm not sure what is better way to do on windows

**Comment by AlexAlabyev** [comment]
@KELiON sorry, what is the question are you referring to? Are you asking whether or not I can open the search bar after triggering the error on Windows? If that's what you meant, the answer is no, I have to close the cerebro app and restart it every time this error pops up. 
(The error can be triggered by `alt + f4` while search bar is opened)

**Comment by AlexAlabyev** [comment]
@KELiON do you think this function might resolve the problem?: [https://github.com/jprichardson/electron-window/blob/master/lib/main.js#L25](https://github.com/jprichardson/electron-window/blob/master/lib/main.js#L25)

**Comment by AlexAlabyev** [comment]
@KELiON @maximbaz these guys here [https://github.com/tinytacoteam/zazu](https://github.com/tinytacoteam/zazu) are using a different approach and their app's search bar doesn't have this issue, it is getting closed only by pressing `Esc` or clicking outside the window. In their case `alt + f4` is closing the app itself (not only the search bar), I think that's how it should be for Cerebro as well. What do you think of that guys?
