### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by hirnschallsebastian** [KELiON/cerebro#477]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macos 10.14 mojave
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: n/a

## Issue

when I try to open the app I get the following error message once I click ok (the only option available) the app is closed.

`Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/lib/trackEvent.js:31:15)
    at module.exports.exports.default (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow.js:166:3)
    at App.module.exports._electron.app.on (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main.development.js:38:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)`

**Comment by hirnschallsebastian** [comment]
duplicate of #470.

**Comment by hirnschallsebastian** [comment]
duplicate of #470 :/
