### ISSUE TITLE
postinstall fails on node v7

### ISSUE THREAD

**Issue by staff0rd** [KELiON/cerebro#6]
~~~
> concurrently "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[0]
[0] assert.js:85
[0]   throw new assert.AssertionError({
[0]   ^
[0] AssertionError: Current node version is not supported for development, expected "7.4.0" to satisfy "6.x".
[0]     at Object.<anonymous> (C:\git\cerebro\node_modules\fbjs-scripts\node\check-dev-engines.js:39:3)
[0]     at Module._compile (module.js:571:32)
[0]     at Object.Module._extensions..js (module.js:580:10)
[0]     at Module.load (module.js:488:32)
[0]     at tryModuleLoad (module.js:447:12)
[0]     at Function.Module._load (module.js:439:3)
[0]     at Module.runMain (module.js:605:10)
[0]     at run (bootstrap_node.js:420:7)
[0]     at startup (bootstrap_node.js:139:9)
[0]     at bootstrap_node.js:535:3
[0] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 1
~~~

**Comment by KELiON** [comment]
@staff0rd it is problem with your local node version. This application currently works with node version 6.x (i.e I'm using v6.5.0) and npm version 3. 

It is required because electron includes the same versions and installed modules with native extensions should be built with the same version. 

To solve this problem you can use [nvm](https://github.com/creationix/nvm) or [n](https://github.com/tj/n) to manage several node version on your machine and use node version 6.5.0 to install modules and run the app

**Comment by staff0rd** [comment]
Indeed, that's one way I ended up getting it going, however the readme states 7 is supported;

> Note: requires a node version >= 6 and an npm version >= 3.

Additionally, it is only the presence of the postinstall script that causes it to fail.  The app still runs in v7, so is just removing the postinstall an option?

**Comment by KELiON** [comment]
@staff0rd it works with node_modules in root folder, but not in `./app/`. Inside `./app` folder, `node_modules` built with native extensions and you have to build these modules with the same node version, that is used by electron.

**Comment by staff0rd** [comment]
I don't follow - running `npm install` from root is what causes the error in node v6.

**Comment by KELiON** [comment]
> running npm install from root is what causes the error in node v6.

@staff0rd so, you have `Current node version is not supported for development` error when you run `npm install` from root on node v6?

**Comment by staff0rd** [comment]
> from root is what causes the error in node v6.

Sorry, I mean't v6.

I see you've updated the readme to target v6 only, which essentially closes this out.  I will note however that removing the `postinstall` script is also a solution, as the application still runs fine in v7.  The `postintall` script seems superfluous.
